### ISSUE TITLE
add some text to image

### ISSUE THREAD

**Issue by mrbontor** [girishpadia/file-crypt-web#1]
how to add some text into image encrypted? is it possible? thanks

**Comment by girishpadia** [comment]
I don't think so. However you can add some text to image and then encrypt it.

**Comment by mrbontor** [comment]
can you explain how to do it to me? or do you have link or references like that? thanks.

**Comment by girishpadia** [comment]
You may use https://en.m.wikipedia.org/wiki/ImageMagick tool to do so. Just
google it.

**Comment by mrbontor** [comment]
thank you @girishpadia .
